---
title: "Rethinking Stastistics - exercises"
---

Date: **December 2024**

------------------------------------------------------------------------

This website documents the efforts to do the exercises of Richard McElreath's "Rethinking statistics", *ed.2*. We build on the following efforts: 

We read: [Rethinking Statistics, second edition](https://xcelab.net/rm/). The book has been "translated" into using [brms](https://github.com/paul-buerkner/brms) and the [tidyverse](https://www.tidyverse.org/) by [Solomon Kurz](https://bookdown.org/content/4857/), and we rely on his code. 

There is a [lecture-series](https://www.youtube.com/watch?v=cclUd_HoRlo&list=PLDcUM9US4XdMROZ57-OIRtIK0aOynbgZN&index=2) to go along with the book. 

To the date of this writing, there are solutions to the excersises online, but only [using the original rethinking package](https://sr2-solutions.wjakethompson.com/bayesian-inference#chapter-2). In an effort to self-teach ourselves, we read the textbook and go through the exercises together. On this website, we collect our efforts. 

The website was built using the [qrtAcademic template](https://andreaczhang.github.io/qtwAcademic/).

# Who are we?

A group of post-docs and phd-students at the Centre for Development and Environment at the University of Bern. 

# Disclaimer

We do our best but will make mistakes along the way. If you find them, congratulations! Also, please tell us, so we can fix them. 

# Licence

CC-BC 4.0

